version: "3.8"
services:
  app:
    image: eldplat_monorepo
    command: turbo run dev
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./apps/workshop/src:/usr/src/app/apps/workshop/src
      - ./apps/Eldplat_Admin:/usr/src/app/apps/Eldplat_Admin
      - ./apps/Eldplat_Client:/usr/src/app/apps/Eldplat_Client
      - ./packages/baseui:/usr/src/app/packages/baseui
      - /app/node_modules
      # - /app/.next
    ports:
      - "3000:3000"
      - "3001:3001"
      - "6006:6006"
    environment:
      - CHOKIDAR_USEPOLLING=true
